### ISSUE TITLE
Compliant access control

### ISSUE THREAD

**Issue by domq** [epfl-sti/wordpress.plugin.accred#1]
* All sites should belong to exactly one unit (whose ID should be settable through wp_cli or a single row in the wp_options table)
* For "admin" and "editor" roles, either Accred should be the only authoritative source of truth for granting, or it should be possible to lock down the config so that it is
* For "viewer" role, it should be possible to use a group instead (as is the case in the current implementation)

**Comment by domq** [comment]
All done as of v0.5

**Comment by ponsfrilus** [comment]
@domq 👍
