### ISSUE TITLE
Bug dans le contrôle d'accès par groupe

### ISSUE THREAD

**Issue by GregLeBarbar** [epfl-sti/wordpress.plugin.accred#3]
Lorsque l'on utilise un groupe pour le rôle administrateur, c'est le rôle éditeur (à vérifier) qui est pris en compte. 

On suspecte que cela peut être lié à la fonction supprimée ci-dessous :

```
function get_access_level($groups)		
 {		
         foreach ($this->settings->get_acls() as $role => $role_setting) {		
             if (in_array($role_setting, $groups)) {		
                 return $role;		
                 break;		
             }		
         }		
         return null;		
 }
```

**Comment by domq** [comment]
Bonjour, merci pour ce rapport de bogue. Arrivez-vous à préciser
• Comment reproduire le problème, étape par étape,
• Ce que vous espériez qu'il allait se passer,
• Ce qui s'est passé effectivement ?

Merci d'avance, Dominique

**Comment by GregLeBarbar** [comment]
Hello,

> Comment reproduire le problème, étape par étape

1. Tu peux te connecter sur le site
https://env-lv-os-exopge.epfl.ch/site13/wp-admin/
user: admin
pwd: admin

2. Vérifier que la config accred a bien le groupe wp_test_auth dans le
champ administrateurs.
On t'a ajouté a ce groupe pour tester.

3. Lorsque que tu te connecte avec ton compte gaspard tu ne devrais pas
avoir les droits d'amin.


A dispo si tu as besoin de plus d'infos

Luc et Greg
